### ISSUE TITLE
Add tutorial mentioned in stub

### ISSUE THREAD

**Issue by matthewfeickert** [reanahub/docs.reana.io#143]
:wave: Hi. With my ATLAS Analysis Preservation Contact hat on :billed_cap:, I've gotten some feedback from users that going from the (nice) ["First example" page](https://docs.reana.io/getting-started/first-example/) and then clicking on the "In-depth tutorial" to find it [empty](https://github.com/reanahub/docs.reana.io/blob/ca6babc3f51ab378a44a1b58335e894909d5eae1/docs/getting-started/tutorial/index.md) can be a bit confusing and causes people to abandon the rest of the docs. It would be useful if this tutorial could either be written, or if that isn't within time scope right now (which is reasonable), if these mentions (and other sections of the docs that aren't filled in yet) could be removed so that the only user facing docs are on subjects that have actionable information for users.

I am also at a shortage of time until maybe early 2023, else I would volunteer to help out with writing the tutorial.

**Comment by tiborsimko** [comment]
Hi @matthewfeickert, thanks for the feedback, we have seen some increase in new user tokens, so this is a perfectly reasonable and well-timed request. We have some content, I'll take care of expanding the stubs within a week or so.

**Comment by matthewfeickert** [comment]
That's excellent news, @tiborsimko, so thanks for taking this on! I really appreciate it and I also understand that there's plenty of other other work that needs to get done as well. If there are small things that I can help out with as well I'm happy to contribute time where I can, and I'll work to collect questions and confusion points from ATLAS users and see if I can upstream them to wherever the REANA team finds the most appropriate. :+1:
