### ISSUE TITLE
docs: Deploy locally

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/docs.reana.io#17]
Populate http://docs.reana.io/development/deploying-locally/

**Comment by diegodelemos** [comment]
Shall we add documentation for the command to create users here or add a new section with common recipes?

Stemmed from https://github.com/reanahub/reana-cluster/pull/261

**Comment by tiborsimko** [comment]
For the user creation, let's add it elsewhere, it's more about deploying at scale... Deploying locally often means single-user development-only scenario.
