### ISSUE TITLE
Keytab instructions are outdated/don't work anymore

### ISSUE THREAD

**Issue by clelange** [reanahub/docs.reana.io#173]
The instructions at https://docs.reana.io/advanced-usage/access-control/kerberos/#generating-keytab-file don't seem to be working anymore. The better way to do this at CERN is described at https://cern.service-now.com/service-portal?id=kb_article&n=KB0003405

**Comment by tiborsimko** [comment]
Thanks for reporting! Interestingly, LXPLUS7 and LXPLUS9 are OK using the new way, but LXPLUS8 is not:

```console
$ cern-get-keytab --keytab mytest8.kt --user --login johndoe
Password for johndoe:
/usr/bin/chcon: failed to change context of 'mytest8.kt' to ‘system_u:object_r:krb5_keytab_t:s0’: Operation not supported
```

Anyway I'll update the docs.

**Comment by clelange** [comment]
I think the issue is also that if you use the current instructions, you can create the keytab, but using it won't work.

**Comment by tiborsimko** [comment]
Everything works well for me with a keytab that I generated long time ago... But I'll retest with a freshly generated one. Thanks for the heads-up.

**Comment by tiborsimko** [comment]
> But I'll retest with a freshly generated one. 

... confirm it works with a freshly generated keytab file on LXPLUS7.

**Comment by clelange** [comment]
For me:

```shell
[clange@lxplus781]~% ktutil
ktutil:  add_entry -password -p clange@CERN.CH -k 1 -e aes256-cts-hmac-sha1-96
Password for clange@CERN.CH:
ktutil:  add_entry -password -p clange@CERN.CH -k 1 -e arcfour-hmac
Password for clange@CERN.CH:
ktutil:  write_kt .keytab
ktutil:  exit
[clange@lxplus781]~% kinit -kt ~/.keytab clange@CERN.CH
kinit: Preauthentication failed while getting initial credentials
```

**Comment by tiborsimko** [comment]
Yes, the PR #174 fixes these generation instructions, so everything should be OK now.  (By "confirm it works with a freshly generated keytab file " I meant using the new generation technique!)
