### ISSUE TITLE
docs: Deploy at scale

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/docs.reana.io#18]
Populate http://docs.reana.io/development/deploying-at-scale

**Comment by diegodelemos** [comment]
All the work in https://github.com/reanahub/reana/pull/276 can be tested with:
```console
$ REANA_COMPONENT_PREFIX=my-reana make deploy
```

**Comment by diegodelemos** [comment]
Note that https://github.com/reanahub/docs.reana.io/pull/32 is on hold until we make a release of REANA chart.

**Comment by diegodelemos** [comment]
Reopening as https://github.com/reanahub/docs.reana.io/pull/32 is still not merged (the rest of the PRs contained `closes` to link the PR with the issue in the kanban board).
