### ISSUE TITLE
devops: deploy on docs.reana.io

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/docs.reana.io#2]
Create `docs.reana.io` web site on OpenShift. 

Use simple manual builds, or enable automatic deployment after each commit.

**Comment by mvidalgarcia** [comment]
Automatic deployment tested successfully. We just need to copy the URL that OpenShift provides you in the build configuration page and create a webhook on GitHub with it. More info [here](https://docs.openshift.com/container-platform/3.11/dev_guide/builds/triggering_builds.html#github-webhooks).

**Comment by diegodelemos** [comment]
Automatic setup configured on OpenShift thanks to @mvidalgarcia work, only missing the correct redirects.
