### ISSUE TITLE
docs: reana-client Python API

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/docs.reana.io#23]
Ditto as #22 but for Python API.

http://docs.reana.io/reference/reana-client-python-api

**Comment by tiborsimko** [comment]
Option 1: We can check whether we can easily generate Python APIs on RTFD. However, Python APIs themselves would not provide "the flow", only the reference. So perhaps we can focus on the "flow" style of docs instead, that would reach out to more users.

Option 2: We can prepare an extensive page describing a "how to" guide about how to use Python APIs. 
What we currently have in the "flow" docs style is the following forum post describing Python API usage flow:

- https://forum.reana.io/t/python-api-to-run-workflows-on-reana/19/2

What we should do is roughly the following:

- check whether instructions are still OK
- and, using roofit and yadage as an example still, and using 0.7.0 as reference REANA version, we have two options:
- option 2a: prepare an expanded, commented, illuminated page for `docs.reana.io`
- option 2b: prepare an expanded, commented, illuminated blog post for `blogs.reana.io`

**Comment by tiborsimko** [comment]
Regarding option 1, we currently have:

```console
$ less docs/index.rst
...
API docs
========

.. automodule:: reana_client.api.client
  :members: create_workflow_from_json, upload_file, start_workflow, download_file
```

We need to enrich it with all the interesting functions mentioned in the blog post.

Ideally, gettting status, listing all workflows, etc... Basically everything that we offer as "nice API" should be included there.

**Comment by mvidalgarcia** [comment]
Closed by https://github.com/reanahub/reana-client/pull/495 🎆 

Docs here: https://reana-client.readthedocs.io/en/latest/#module-reana_client.api.client
