### ISSUE TITLE
docs: create a dedicated "For developers" page

### ISSUE THREAD

**Issue by VMois** [reanahub/docs.reana.io#91]
REANA is a complex system, making it easier for developers to start contributing to it will definitely help the project.
For this, we can create a dedicated "For developers" page to provide all necessary information for new contributors. The page should improve the developer experience. Example of the information that can appear on this page:

- how to set up a development environment and cluster ([here](http://docs.reana.io/administration/deployment/deploying-locally/#for-developers) is an existing resource but it is "hidden" under "Administration" page)
- guidelines for code formatting and how to contribute
- tips and tricks on how to debug the cluster or use `reana-dev` tool
- architecture of the REANA cluster and how different components interact

Examples of similar "For developers" pages:

- [Dask Distributed "Developer documentation"](https://distributed.dask.org/en/latest/communications.html)
- [React "Contribution" page](https://reactjs.org/docs/how-to-contribute.html)

We can start small by moving already existing resources for developers to a dedicated page. Thank you.

**Comment by tiborsimko** [comment]
Two thoughts on this:

(1) Note that we used to have some developer-oriented pages on docs.reana.io but that we had discussed moving all developer-oriented information into GitHub Wiki. This was done for some pages, e.g. see "how to debug" https://github.com/reanahub/reana/wiki/Debugging

The motivation for separating researcher-level documentation from developer-level documentation is simple: not to make a deluge of information for researchers that might be searching main REANA docs for how to use (or install/administer) REANA. 
For example, if a search for some concept gives a lot of `reana-dev` hits, users would be confused since they are not seeing this (developer-only)wrapper. Having this on GitHub wiki allows to nicely separate concerns.

(See say https://github.com/reanahub/docs.reana.io/pull/73 and https://github.com/reanahub/docs.reana.io/issues/60 and others for examples of past activities in this direction.

(2) The most important tips and tricks for using `reana-dev` should be all documented in `reana-dev --help`, see the beginning of that command's output. Is this enough? Would you like to see there something else? We can definitely enrich it. Or have you been thinking of moving this kind of information fully to the developer wiki?  That might also be OK, but then we may need to think about keeping  the info in sync.  Since the number of contributors to REANA is rather small and well localised, as opposed to say React, keeping the reana-dev info in CLI help might do?

**Comment by VMois** [comment]
(1) 
**1.1** *opinion*: It would be nice to have all docs in `docs.reana.io` because we can keep all of them in one repo (single place, easy to maintain) instead of having a separate website and wiki (sync between docs and wiki is an issue and no easy way to [version docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#versioning)).

**1.2** *question*: issue with searching for some concepts that you mentioned, was it raised by researchers or it is a hypothetical example?

**1.3** *suggestion*: We can leave this issue open for discussion (@mvidalgarcia, @audrium, @mariaFernando, @marcdiazsan  feel free to comment). What I can do right now not to block progress is to:
 
 - create a dedicated "For developers" page on `docs.reana.io` and write only "All developers docs are in our wiki, please refer to [GitHub wiki link here]". From my personal experience, I didn't find a wiki page on my first look at REANA docs and was thinking it is missing or internal. 
 - move the remaining "Deploying locally => for developers" to a wiki page so all developer-related resources will be in the wiki.
 
 What do you think?
 
 (2)
 **2.1** *opinion*: Yep, now I found it. It overflows my screen so I couldn't see it. So... we will have `docs.reana.io` for users + wiki for devs + `reana-dev help` for dev examples? Feels like a lot of places to me.

**Comment by mvidalgarcia** [comment]
I agree that it would be nice to have richer developer/contributing docs somewhere. But I'm not sure if keeping those hosted at docs.reana.io is the best solution. Said that, I agree that the wiki isn't the best place, or at least it's not easy to find, so having some links pointing to it in docs.reana.io might be a good solution/workaround. This way we don't _pollute_ the user docs with stuff that is not interesting to them.

See for instance how Invenio keeps links to Contributing guidelines, but they are not hosted in the same place - https://inveniosoftware.org/documentation/

In addition, we have [CONTRIBUTING](https://github.com/reanahub/reana/blob/master/CONTRIBUTING.rst) files in all the repos, basically repeating the very same content, which I'm not sure if it really makes sense... Maybe this can be centralized somewhere.

**Comment by VMois** [comment]
*suggestion*: I want to keep developer docs under git versioning and also I can understand the idea of separating the docs.
So, this is a compromise:

1. we can host developer docs under a different subdomain e.g `developers.reana.io` (actually, pretty nice name)

2. we will keep `developers.reana.io` in `reana` repository. In this case, it is (a) under git, (b) is versioned (new REANA cluster release, new docs release too).

3. we can add a link to `docs.reana.io` to point to `developers.reana.io`.

What do you think?

**Comment by mvidalgarcia** [comment]
In my opinion, having yet another repo for docs would be too much, as we'd need to set up a new site, customize it, deploy it etc. We're already struggling to keep up with docs.reana.io, www.reana.io, blog.reana.io to introduce a new one.

**Comment by VMois** [comment]
I see. So, if we don't want to put developers' docs to `docs.reana.io` and creating a dedicated website will introduce more maintenance load then let's put the docs to GitHub Wiki. We can add link to `docs.reana.io` pointing to docs.

**Comment by mvidalgarcia** [comment]
It's just my opinion, doesn't need to be like that. Unfortunately, I don't have a nice solution at the moment in my mind... we should discuss it all together. Please, bring the topic to the table next week so we can agree on something.

**Comment by tiborsimko** [comment]
> I see. So, if we don't want to put developers' docs to `docs.reana.io` and creating a dedicated website will introduce more maintenance load then let's put the docs to GitHub Wiki.

That's exactly what I had mentioned above that our docs strategy was: (1) keep docs.reana.io for researcher-oriented docs, and (2) use GitHub wiki for developer-oriented docs. So, for example, if you are missing some interesting tips for developers about macOS docker memory setup, or how to add metrics server, etc, we can start creating new wiki pages to enrich the current there.

(E.g. I'll take care about some of the ones you mentioned above related to contributing and review practices; we have some material offline for that.)

**Comment by mvidalgarcia** [comment]
So, summarizing, what are the actions to be performed? @tiborsimko

**Comment by VMois** [comment]
Actions: our developer documentation will be on GitHub Wiki, we can start continuously enhancing it. General advice for everyone is to be proactive :) 

 PR related to this issue was merged. It moved all developers related information from `docs.reana` to GitHub Wiki. In addition, it also added a small section to `docs.reana` to link to GitHub Wiki in case some contributors will be interested.
 
 I don't see a point in keeping this issue open. Thank you.

**Comment by mvidalgarcia** [comment]
> @mvidalgarcia: Said that, I agree that the wiki isn't the best place, or at least it's not easy to find...

Sorry for bitching again on this, I still don't find it pretty nice.. I guess we can live with it for now.. but it's not good not to keep it (properly) under version control, code reviews, etc. in my opinion. It's basically impossible to keep up with the changes that happen there without checking the wiki periodically.

**Comment by tiborsimko** [comment]
> it's not good not to keep it (properly) under version control

GitHub wiki can be worked with via git, so that might be covered relatively nicely. What we might be missing is doc reviews, and alertness, which is indeed an issue...

**Comment by VMois** [comment]
Yep. It would be nice to have code reviews and, as I wrote before, I would prefer to have docs together with a code instead of a separate repo. 

Our public developer's docs are only starting to grow so it is fine for now but we will need a different solution in a long term.

Should we create a dedicated issue for the future? This one intended to create a place for docs and it is done

**Comment by mvidalgarcia** [comment]
Maybe just keeping a bare metal mkdocs/GitLab Static pages can be a solution (https://how-to.docs.cern.ch/) But creating another repo seems too much to me...

**Comment by VMois** [comment]
That is what I was thinking, adding dev docs to `reana` repo and have a `developers.reana.io` website. It will take some time to set up though.

I don't think the GitLab static page is a good solution. Developers docs are created for everyone: core team, contributors, etc. So better to keep them close to the codebase.

**Comment by mvidalgarcia** [comment]
Another options is https://reana.readthedocs.io/en/latest/

**Comment by VMois** [comment]
This looks good - free space to put developers' docs. We can also adapt `mkdocs` if it is quick, to align with `docs.reana`.

**Comment by mvidalgarcia** [comment]
I'm afraid `mkdocs` requires an additional repo, which is what we want to avoid... unless you have something else in mind
ReadTheDocs relies on Sphinx and reStructuredText, not a big fan 😕 but it comes for free.. (hosting, deployment..)

**Comment by tiborsimko** [comment]
We have decided to use [GitHub wiki](https://github.com/reanahub/reana/wiki) for all developer-level documentation. The wiki will be soon revamped and populated.
