### ISSUE TITLE
List versions of CWL supported?

### ISSUE THREAD

**Issue by mr-c** [reanahub/docs.reana.io#99]

**Comment by tiborsimko** [comment]
Hi @mr-c, we should definitely improve the REANA documentation in this respect.

Latest REANA 0.8 release series uses `cwltool==3.1.20210628163208`.

Eearlier REANA 0.7 release series used `cwltool==1.0.20191022103248`.

**Comment by mr-c** [comment]
Thanks @tiborsimko . Using a particular version of `cwltool` as a library does not automatically mean that particular versions of CWL is fully supported, hence the requests to run the CWL conformance tests and report the results (even if only manually, once per release)

https://github.com/reanahub/reana-workflow-engine-cwl/issues/168

**Comment by tiborsimko** [comment]
CC @audrium who has been dealting with running the CWL reference test suite lately. We'll upgrade the REANA documentation for each supported workfolw engine and we'll have a look specifically at reporting the CWL conformance test suite results afterwards.

**Comment by audrium** [comment]
Hi @mr-c, we have just reran the conformance test suite on the latest REANA version and the results are as follows:
```
179 tests passed, 18 failures, 0 unsupported features
1 tool tests failed
```
The failures are documented in the [reana-workflow-engine-cwl](https://github.com/reanahub/reana-workflow-engine-cwl/issues) issues if you want to have a look.

We are planning to work on exposing these results in REANA documentation in the upcoming weeks
